# Format where the key is the question/prompt. The value is the accepted response.
user_prompts: dict[str, str] = {
    "Quick! Repeat after me! Say `​s​﻿u​﻿p​﻿e​﻿r​﻿c​﻿a​﻿l​﻿i​﻿f​﻿r​﻿a​﻿g​﻿i​﻿l​﻿i​﻿s​﻿t​﻿i​﻿c​﻿e​﻿x​﻿p​﻿i​﻿a​﻿l​﻿i​﻿d​﻿o​﻿c​﻿i​﻿o​﻿u​﻿s`!": "supercalifragilisticexpialidocious",
    "Quick! Repeat after me! Say `​m​﻿a​﻿c​﻿a​﻿d​﻿a​﻿m​﻿i​﻿a`!": "macadamia",
    "Quick! Repeat after me! Say `​j​﻿o​﻿h​﻿n`!": "john",
    "Quick! Repeat after me! Say `​p​﻿n​﻿e​﻿u​﻿m​﻿o​﻿n​﻿u​﻿l​﻿t​﻿r​﻿a​﻿m​﻿i​﻿c​﻿r​﻿o​﻿s​﻿c​﻿o​﻿p​﻿i​﻿c​﻿o​﻿s​﻿i​﻿l​﻿i​﻿c​﻿o​﻿v​﻿o​﻿l​﻿c​﻿a​﻿n​﻿o​﻿c​﻿o​﻿n​﻿i​﻿o​﻿s﻿i﻿s`!": "pneumonoultramicroscopicsilicovolcanoconiosis",
    "Quick! Repeat after me! Say '​l​​﻿o​﻿l​﻿y​﻿o​﻿u​﻿h​﻿a​﻿d​﻿t​﻿o​﻿t​﻿y​﻿p​﻿e​﻿a​﻿l​﻿l​﻿t​﻿h​﻿i​﻿s'!": "lolyouhadtotypeallthis",
    "Quick! Repeat after me! Say `​h​﻿a​﻿r​﻿r​﻿y​﻿i​﻿s​﻿a​﻿w​﻿i​﻿z​﻿a​﻿r​﻿d`!": "harryisawizard",
    "Quick! Repeat after me! Say `​c​﻿o​﻿l​﻿l​﻿e​﻿c​﻿t'!": "collect",
    "Quick! Repeat after me! Say `​g​﻿r​﻿a​﻿b`!": "grab",
    "Quick! Repeat after me! Say `​m​﻿i​﻿n​﻿e`!": "mine",
    "Quick! Repeat after me! Say `​n​﻿a​﻿b`!": "nab",
    "Quick! Repeat after me! Say `​p​﻿i​﻿c​﻿k`!": "pick",
    "Quick! Repeat after me! Say `​s​﻿n​﻿a​﻿t​﻿c​﻿h`!": "snatch",
    "Quick! Repeat after me! Say `​y​﻿o​﻿i​﻿n​﻿k`!": "yoink",
    "Quick! Repeat after me! Say `​y​﻿u​﻿m`!": "yum",
    "Quick! Repeat after me! Say `​g​﻿i​﻿v​﻿e​﻿m​﻿e​c​﻿o​﻿o​﻿k​﻿i​﻿e`!": "givemecookie",
    "Quick! Repeat after me! Say `​s​﻿t​﻿e​﻿a​﻿l`!": "steal",
    "Quick! Repeat after me! Say `​k​﻿i​﻿d​﻿n​﻿a​﻿p`!": "kidnap",
    "Quick! Repeat after me! Say `​n​﻿o​﻿m`!": "nom",
    "Quick! Repeat after me! Say `​t​﻿a​﻿s​﻿t​﻿y`!": "tasty",
    "Quick! Repeat after me! Say `​g​﻿i​﻿n​﻿g​﻿e​﻿r​﻿b​﻿r​﻿e​﻿a​﻿d`!": "gingerbread",
    "Quick! Repeat after me! Say `​s​﻿n​﻿i​﻿c​﻿k​﻿e​﻿r​﻿d​﻿o​﻿o​﻿d​﻿l​﻿e`!": "snickerdoodle",
    "Quick! Repeat after me! Say `​o​﻿a​﻿t​﻿m​﻿e​﻿a​﻿l​﻿r​﻿a​﻿i​﻿s​﻿i​﻿n'!": "oatmealraisin",
    "Quick! Repeat after me! Say `​c​﻿h​﻿o​﻿c​﻿o​﻿l​﻿a​﻿t​﻿e​ ﻿c​﻿h​﻿i​﻿p`!": "chocolate chip",
    "Quick! Repeat after me! Say `​g​﻿i​﻿n​﻿g​﻿e​﻿r​﻿s​﻿n​﻿a​﻿p`!": "gingersnap",
    "Quick! Repeat after me! Say `​s​﻿h​﻿o​﻿r​﻿t​﻿b​﻿r​﻿e​﻿a​﻿d`!": "shortbread",
    "Quick! Repeat after me! Say `​p​﻿e​﻿a​﻿n​﻿u​﻿t​﻿b​﻿u​﻿t​﻿t​﻿e​﻿r`!": "peanutbutter",
    "Quick! Repeat after me! Say `​s​﻿u​﻿g​﻿a​﻿r`!": "sugar",
    "Quick! Repeat after me! Say `​b​﻿i​﻿s​﻿c​﻿o​﻿t​﻿t​﻿i`!": "biscotti",
    "Quick! Repeat after me! Say `​m​﻿a​﻿c​﻿a​﻿r​﻿o​﻿o​﻿n`!": "macaroon",
    "Quick! Repeat after me! Say `​m​﻿a​﻿c​﻿r​﻿o​﻿n​﻿s`!": "macrons",
    "Quick! Repeat after me! Say `​s​﻿p​﻿i​﻿c​﻿e`!": "spice",
    "Quick! Repeat after me! Say `​i​﻿r​﻿o​﻿n​﻿m​﻿a​﻿n`!": "ironman",
    "Quick! Repeat after me! Say `​i​﻿m​﻿b​﻿a​﻿t​﻿m​﻿a​﻿n`!": "imbatman",
    "Quick! Repeat after me! Say `​l​﻿o​﻿l​﻿a​﻿n​﻿d​﻿r​﻿o​﻿i​﻿d`!": "lolandroid",
    "Quick! Repeat after me! Say `​i​﻿m​﻿g​﻿o​﻿i​﻿n​﻿g​﻿t​﻿o​﻿s​﻿l​﻿e​﻿e​﻿p`!": "imgoingtosleep",
    "Quick! Repeat after me! Say `​d​﻿r​﻿i​﻿n​﻿k​﻿w​﻿a​﻿t​﻿e​﻿r`!": "drinkwater",
    "Quick! Repeat after me! Say `​b​﻿l​﻿o​﻿x​﻿l​﻿i​﻿n​﻿k`!": "bloxlink",
    "Quick! Repeat after me! Say `​i​﻿m​﻿a​﻿m​﻿a​﻿z​﻿i​﻿n​﻿g`!": "imamazing",
    "Quick! Repeat after me! Say `​w​﻿h​﻿a​﻿t​﻿t​﻿a​﻿b​﻿u​﻿r​﻿g​﻿e​﻿r`!": "whattaburger",
    "Quick! Repeat after me! Say `​b​﻿i​﻿g​﻿m​﻿a​﻿c​﻿s​﻿u​﻿p​﻿r​﻿e​﻿m​﻿e`!": "bigmacsupreme",
    "Quick! Repeat after me! Say `​s​﻿u​﻿n​﻿n​﻿y`!": "sunny",
    "Quick! Repeat after me! Say `​g​﻿a​﻿l​﻿l​﻿e​﻿t​﻿a`!": "galleta",
    "Quick! Repeat after me! Say `​n​﻿u​﻿b​﻿n​﻿u​﻿b​﻿n​﻿u​﻿b`!": "nubnubnub",
    "Quick! Repeat after me! Say `​i​﻿m​﻿t​﻿h​﻿e​﻿l​﻿o​﻿r​﻿a​﻿x`!": "imthelorax",
    "Quick! Repeat after me! Say `​f​﻿i​﻿s​﻿h​﻿i​﻿e​﻿s`!": "fishies",
    
    "What's 2+2? *(hint: 'four')*": "4",
    "What's 9+10? *(hint: 'yo stupid')*": "21",
}
